function getMockData(type) {
    switch (type) {
        case 'build':
            return getBuildDataMock();
        case 'map':
            return getMapDataMock();
    }
}

function getMapMessMockData() {
    return mapMessMock;
}


function getBuildDataMock() {
    return buildDataMock;
}

function getMapDataMock() {
    return mapDataMock;
}

function getBaseMapMock() {
    return baseMapMock;
}

function getMapDetailMock() {
    return mapDetailMock;
}

function getNetDevComMock() {
    return netComDevMock;
}

function getBuildMapRelMock() {
    return buildMapRelMock;
}

function getNetworkMock() {
    return networkMock;
}

function getAnchorMock() {
    return anchorMock;
}

//url: 'http://127.0.0.1:8083/geoserver/hzmap/wms',
var mapMessMock = {
    code: 'EPSG:404000',
    host: 'http://127.0.0.1:8083',
    serverType: 'geoserver',
    workspace: 'hzmap',
    requestType: 'wms',
    layers: 'gdata_1_1_plane',
    x_min: -10.153,
    y_min: 4.394,
    x_max: 77.846,
    y_max: 71.617,
    zoom_default: 1,
    zoom_max: 5,
    zoom_min: 1.2,
}


var buildDataMock = {
    "code": 0,
    "message": "操作成功",
    "success": true,
    "map": {},
    "obj": {
        "pageNum": 1,
        "pageSize": 1,
        "size": 1,
        "orderBy": null,
        "startRow": 0,
        "endRow": 0,
        "total": 1,
        "pages": 1,
        "list": [{
            "bid": 1,
            "descrip": "测试",
            "address": "湖北省武汉市某某区",
            "name": "教学楼2号",
            "x": 114.271241,
            "y": 30.447683,
            "height": 6,
        }],
        "firstPage": 1,
        "prePage": 0,
        "nextPage": 0,
        "lastPage": 1,
        "isFirstPage": true,
        "isLastPage": true,
        "hasPreviousPage": false,
        "hasNextPage": false,
        "navigatePages": 8,
        "navigatepageNums": [1]
    }
}

var mapDataMock = {
    "code": 0,
    "message": "操作成功",
    "success": true,
    "map": {},
    "obj": {
        "pageNum": 1,
        "pageSize": 2,
        "size": 2,
        "orderBy": null,
        "startRow": 0,
        "endRow": 1,
        "total": 2,
        "pages": 1,
        "list": [{
            "mapId": 1,
            "title": "教学楼2号-4F",
            "status": 1,
            "descrip": "",
            "createTime": "2018年11月14日 05:22",
            "updateTime": "2018年11月14日 05:22",
            "floor": 4,
            "buildName": "教学楼2号",
            "bid": 1
        }, {
            "mapId": 2,
            "title": "教学楼2号-4F(废弃)",
            "status": 0,
            "descrip": "",
            "createTime": "2018年11月19日 08:05",
            "updateTime": "2018年11月19日 08:05",
            "floor": 0,
            "buildName": null,
            "bid": 0
        }],
        "firstPage": 1,
        "prePage": 0,
        "nextPage": 0,
        "lastPage": 1,
        "isFirstPage": true,
        "isLastPage": true,
        "hasPreviousPage": false,
        "hasNextPage": false,
        "navigatePages": 8,
        "navigatepageNums": [1]
    }
}

var baseMapMock = {
    "code": 0,
    "message": "操作成功",
    "success": true,
    "map": {},
    "obj": {
        "mapId": 1,
        "code": "EPSG:404000",
        "host": "http://127.0.0.1:8083",
        "serverType": "geoserver",
        "workspace": "hzmap",
        "requestType": "wms",
        "layers": "gdata_1_1_plane",
        "x_min": -10.153,
        "x_max": 77.846,
        "y_min": 4.394,
        "y_max": 71.617,
        "zoom_default": 1.0,
        "zoom_max": 5.0,
        "zoom_min": 1.2
    }
}

var mapDetailMock = {
    "code": 0,
    "message": "操作成功",
    "success": true,
    "map": {},
    "obj": {
        "mapId": 1,
        "title": "教学楼2号-4F",
        "status": 1,
        "descrip": "",
        "createTime": "2018年11月14日\n\t\t05:22",
        "updateTime": "2018年11月14日 05:22",
        "floor": 4,
        "height": 6,
        "buildName": "教学楼2号",
        "bid": 1
    }
}

var netComDevMock = {
    "code": 0,
    "message": "操作成功",
    "success": true,
    "map": {},
    "obj": {
        "coordinators": [{
            "coorId": 1,
            "status": 1,
            "sn": "CAE8601001",
            "bid": 1,
            "nid": 1,
            "floor": 4
        }, {
            "coorId": 1,
            "status": 1,
            "sn": "CAE8601001",
            "bid": 1,
            "nid": 1,
            "floor": 4
        }, {
            "coorId": 1,
            "status": 1,
            "sn": "CAE8601001",
            "bid": 1,
            "nid": 1,
            "floor": 4
        }, {
            "coorId": 1,
            "status": 1,
            "sn": "CAE8601001",
            "bid": 1,
            "nid": 1,
            "floor": 4
        }, {
            "coorId": 1,
            "status": 1,
            "sn": "CAE8601001",
            "bid": 1,
            "nid": 1,
            "floor": 4
        }],
        "sinks": [{
            "sinkId": 1,
            "status": 1,
            "sn": "SAE8601001",
            "bid": 1
        }]
    }
}

var buildMapRelMock = {
    "code": 0,
    "message": "操作成功",
    "success": true,
    "map": {},
    "obj": [{
        "bid": 1,
        "floor": 4,
        "mapId": 1
    }]
}



var networkMock = {
    "code": 0,
    "message": "操作成功",
    "success": true,
    "map": {},
    "obj": {
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "comStatus": 1,
        "anchorStatus": 2,
        "coorId": 1
    }
}

var anchorMock = {
    "code": 0,
    "message": "操作成功",
    "success": true,
    "map": {},
    "obj": [{
        "anchorId": 1009,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 1,
        "status": 1,
        "x": 2,
        "y": 6,
        "sn": "AAE861009"
    }, {
        "anchorId": 1010,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 1,
        "status": 1,
        "x": 2,
        "y": 60,
        "sn": "AAE861010"
    }, {
        "anchorId": 1011,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 1,
        "status": 1,
        "x": 0,
        "y": 63,
        "sn": "AAE861011"
    }, {
        "anchorId": 1021,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 1,
        "status": 1,
        "x": 0,
        "y": 3,
        "sn": "AAE861021"
    }, {
        "anchorId": 1033,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 1,
        "status": 1,
        "x": 74,
        "y": 60,
        "sn": "AAE861033"
    }, {
        "anchorId": 1034,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 1,
        "status": 1,
        "x": 77,
        "y": 63,
        "sn": "AAE861034"
    }, {
        "anchorId": 1058,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 1,
        "status": 1,
        "x": 74,
        "y": 6,
        "sn": "AAE861058"
    }, {
        "anchorId": 1071,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 1,
        "status": 1,
        "x": 77,
        "y": 3,
        "sn": "AAE861071"
    }, {
        "anchorId": 1001,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861001"
    }, {
        "anchorId": 1002,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861002"
    }, {
        "anchorId": 1003,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861003"
    }, {
        "anchorId": 1004,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861004"
    }, {
        "anchorId": 1005,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861005"
    }, {
        "anchorId": 1006,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861006"
    }, {
        "anchorId": 1007,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861007"
    }, {
        "anchorId": 1008,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861008"
    }, {
        "anchorId": 1012,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861012"
    }, {
        "anchorId": 1013,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861013"
    }, {
        "anchorId": 1014,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861014"
    }, {
        "anchorId": 1015,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861015"
    }, {
        "anchorId": 1016,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861016"
    }, {
        "anchorId": 1017,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861017"
    }, {
        "anchorId": 1018,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861018"
    }, {
        "anchorId": 1019,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861019"
    }, {
        "anchorId": 1020,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861020"
    }, {
        "anchorId": 1022,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861022"
    }, {
        "anchorId": 1023,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861023"
    }, {
        "anchorId": 1024,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861024"
    }, {
        "anchorId": 1025,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861025"
    }, {
        "anchorId": 1026,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861026"
    }, {
        "anchorId": 1027,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861027"
    }, {
        "anchorId": 1028,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861028"
    }, {
        "anchorId": 1029,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861029"
    }, {
        "anchorId": 1030,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861030"
    }, {
        "anchorId": 1031,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861031"
    }, {
        "anchorId": 1032,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861032"
    }, {
        "anchorId": 1035,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861035"
    }, {
        "anchorId": 1036,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861036"
    }, {
        "anchorId": 1037,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861037"
    }, {
        "anchorId": 1038,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861038"
    }, {
        "anchorId": 1039,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861039"
    }, {
        "anchorId": 1040,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861040"
    }, {
        "anchorId": 1041,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861041"
    }, {
        "anchorId": 1042,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861042"
    }, {
        "anchorId": 1043,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861043"
    }, {
        "anchorId": 1044,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861044"
    }, {
        "anchorId": 1045,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861045"
    }, {
        "anchorId": 1046,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861046"
    }, {
        "anchorId": 1047,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861047"
    }, {
        "anchorId": 1048,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861048"
    }, {
        "anchorId": 1049,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861049"
    }, {
        "anchorId": 1050,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861050"
    }, {
        "anchorId": 1051,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861051"
    }, {
        "anchorId": 1052,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861052"
    }, {
        "anchorId": 1053,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861053"
    }, {
        "anchorId": 1054,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861054"
    }, {
        "anchorId": 1055,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861055"
    }, {
        "anchorId": 1056,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861056"
    }, {
        "anchorId": 1057,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861057"
    }, {
        "anchorId": 1059,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861059"
    }, {
        "anchorId": 1060,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861060"
    }, {
        "anchorId": 1061,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861061"
    }, {
        "anchorId": 1062,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861062"
    }, {
        "anchorId": 1063,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861063"
    }, {
        "anchorId": 1064,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861064"
    }, {
        "anchorId": 1065,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861065"
    }, {
        "anchorId": 1066,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861066"
    }, {
        "anchorId": 1067,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861067"
    }, {
        "anchorId": 1068,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861068"
    }, {
        "anchorId": 1069,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861069"
    }, {
        "anchorId": 1070,
        "nid": 1,
        "bid": 1,
        "floor": 4,
        "anchorType": 0,
        "status": 1,
        "x": null,
        "y": null,
        "sn": "AAE861070"
    }]
}